<?php
use Migrations\AbstractMigration;
use Phinx\Db\Adapter\MysqlAdapter;

class AddIndexes extends AbstractMigration
{
    public function change()
    {
        $this->table('cake_api_connector_dataobjects')
            ->addIndex(
                [
                    'foreign_id',
                ]
            )
            ->addIndex(
                [
                    'parent_id',
                    'parent_model',
                ]
            )
            ->addIndex(
                [
                    'entity_id',
                    'entity',
                    'parent_id',
                    'parent_model',
                ]
            )
            ->addIndex(
                [
                    'entity',
                    'entity_id',
                ]
            )
            ->addIndex(
                [
                    'parent_id',
                    'entity',
                ]
            )
            ->addIndex(
                [
                    'parent_id',
                    'parent_model',
                    'entity',
                    'entity_id',
                    'modified',
                ]
            )
            ->addIndex(
                [
                    'foreign_id',
                    'parent_id',
                    'parent_model',
                    'entity',
                    'entity_id',
                    'modified',
                ]
            )
            ->addIndex(
                [
                    'foreign_id',
                    'parent_id',
                    'entity',
                    'name',
                    'status',
                    'modified',
                ]
            )
            ->addIndex(
                [
                    'entity',
                    'name',
                    'modified',
                ]
            )
            ->addIndex(
                [
                    'foreign_id',
                    'entity',
                    'name',
                    'status',
                    'modified',
                ]
            )
            ->addIndex(
                [
                    'foreign_id',
                    'parent_id',
                    'entity',
                    'name',
                    'status',
                    'modified'
                ]
            )
            ->addIndex(
                [
                    'entity',
                    'name',
                    'status',
                    'data',
                ],
                [
                    'limit' => 394,
                ]
            )
            ->addIndex(
                [
                    'name',
                    'status',
                    'modified'
                ]
            )
            ->addIndex(
                [
                    'status',
                    'data',
                ],
                [
                    'limit' => 394,
                ]
            )
            ->addIndex(
                [
                    'site_id',
                    'locale',
                    'entity_id',
                    'entity',
                    'name',
                    'modified'
                ]
            )
            ->addIndex(
                [
                    'name',
                    'entity',
                    'entity_id',
                    'modified'
                ]
            )
            ->addIndex(
                [
                    'foreign_id',
                    'name',
                    'entity',
                    'entity_id',
                    'modified'
                ]
            )
            ->addIndex(
                [
                    'data',
                ],
                [
                    'limit' => 394,
                ]
            )
            ->addIndex(
                [
                    'created',
                ]
            )
            ->addIndex(
                [
                    'modified',
                ]
            )
            ->save();
    }
}
